Add helm charts of newspaper api
Smarp/newspaper-api pull request #28
Opened 2022-02-10 11:32 UTC by gollariel

2022-02-10 11:32 UTC, gollariel commented
@sergey-rozin-smarp Please, let me know if I miss something. Also, I did not test it, I would like to ask for help with testing

2022-02-14 08:06 UTC, sergey-rozin-smarp commented on helm-chart/templates/_helpers.tpl
> +app.kubernetes.io/instance: {{ .Release.Name }}
Oriol might ask you to add
`app: {{ include "helm-chart.name" . }}`
This label is used just for similarity to our current deployments. Also it's interesting why your chart is using "helm-chart" as a base object. May be you used something like "helm create helm-chart" to generate it. I'd prefer to have actual app name here but it's not critical

2022-02-14 08:08 UTC, sergey-rozin-smarp commented on helm-chart/templates/deployment.yaml
> +          livenessProbe:
are these probes correct? Empty path looks suspicious

2022-02-14 08:09 UTC, sergey-rozin-smarp commented on helm-chart/templates/hpa.yaml
> +apiVersion: autoscaling/v2beta1
update it to `autoscaling/v2beta2`. You can use slackapp chart as an example

2022-02-14 08:11 UTC, sergey-rozin-smarp commented on helm-chart/templates/deployment.yaml
> +          livenessProbe:
in values.yaml you define probe paths but they are not used here

2022-02-14 08:26 UTC, sergey-rozin-smarp commented
what about using this helm chart on CI?

2022-02-14 09:20 UTC, orifito requested changes

2022-02-14 09:20 UTC, orifito commented on helm-chart/templates/ingress.yaml
> +{{- if .Values.ingress.enabled -}}
this whole template can be removed.. and the `NOTES.txt` will need to be updated accordingly

2022-02-14 09:20 UTC, orifito commented on helm-chart/values.yaml
> +  #      - chart-example.local
ditto, this can be removed

2022-02-14 09:20 UTC, orifito commented on helm-chart/values.yaml
> +  # We usually recommend not to specify default resources and to leave this as a conscious
please set current resources configured:
```
    Limits:
      cpu:     750m
      memory:  640Mi
    Requests:
      cpu:      400m
      memory:   400Mi
```

2022-02-14 09:20 UTC, orifito commented on newspaper-api.yml
>        containers:
this file should be removed too

2022-03-22 16:00 UTC, orifito commented on helm-chart/values.yaml
> +   limits:
bad indentation here, there's an extra space

2022-03-23 10:51 UTC, orifito requested changes

2022-03-23 10:51 UTC, orifito commented on helm-chart/templates/deployment.yaml
> +              port: {{ .Values.application.livenessProbe.port }}
this is not set / present on the values file

2022-03-23 10:51 UTC, orifito commented on helm-chart/values.yaml
> +  repository: smarp/newspaper-api:v2.4
remove tag from there since it's set in the key below

2022-03-24 14:37 UTC, orifito requested changes
ConfigMap is missing (see last lines of `newspaper-api.yaml`)

2022-03-25 15:32 UTC, orifito approved these changes

2022-03-29 09:02 UTC, merged